[package]
name = "vmm-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
nvmm = { path = "../nvmm" }
env_logger = "0.11"
log = "0.4"
anyhow = "1.0.100"
tokio = { version = "1.0", features = ["full"] }
clap = { version = "4.4.11", features = ["derive"] }
